### ISSUE TITLE
Request for Support of All Groq Models

### ISSUE THREAD

**Issue by jp-moreno** [ad-si/cai#7]
Would it be possible to support the other models available on groq cloud not just mixtral? It would be great to be able to use llama3

**Comment by ad-si** [comment]
Yes! Had it on my todo list already 🙂

Just released 0.6 which includes support for *all* models from Groq, Ollama, OpenAI, and Anthropic!

Let me know if something doesn't work as expected!

**Comment by ad-si** [comment]
Add Groq Llama3 is actually the new default! The speed of Groq and the capabilities of Llama3 is just an awesome combo!
